name: C CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: get-dependencies
      run: sudo apt-get install libsdl2-dev
    - name: make
      run: ./make.sh
    - name: run
      run: echo "No tests have been written yet; the workflow only tests to see if it compiles."

