name: C CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: get-dependencies
      run: sudo apt-get install libsdl2-dev
    - name: make
      run: ./make.sh
    - name: run
      run: ./physics.x86

